name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_PATH: /web-finance-app/pr-preview/pr-${{github.event.number}}

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Get files
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        if: github.event.action != 'closed'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        if: github.event.action != 'closed'
        run: npm ci
      - name: Run tests
        if: github.event.action != 'closed'
        run: npm test
      - name: Build project
        if: github.event.action != 'closed'
        run: npm run build
      - name: Add .nojekyll file
        if: github.event.action != 'closed'
        run: touch ./out/.nojekyll
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: out
          preview-branch: gh-pages
